### ISSUE TITLE
Keyboard Shortcuts 

### ISSUE THREAD

**Issue by codeyash** [speedovation/kiwi#103]
All possible options in shortcuts

And use them

Like locator, project and many important are missing

**Comment by codeyash** [comment]
It's possible to have different key binding to each unique platform as product supports multiple ones.

We should have to maintain a Wiki where we keep this info so that anytime anyone can copy and add more shortcuts

**Comment by codeyash** [comment]
https://github.com/speedovation/kiwi/wiki/Keyboard-Shortcuts

Please update

**Comment by samratchak** [comment]
https://en.wikipedia.org/wiki/Table_of_keyboard_shortcuts

**Comment by codeyash** [comment]
https://www.shortcutfoo.com/app/dojos/webstorm-phpstorm-win/cheatsheet

https://www.shortcutfoo.com/app/dojos/atom-mac/cheatsheet

https://www.shortcutfoo.com/app/dojos/textmate-mac/cheatsheet

https://www.shortcutfoo.com/app/dojos/sublime-text-3-win/cheatsheet

https://www.shortcutfoo.com/app/dojos/emacs/cheatsheet

**Comment by codeyash** [comment]
Keyboard Shortcuts should be added in json file instead of sqlite file.

Why
- Makes possible extending shortcuts easy. 
- Can create copy of any fav version
- Possible to add different editors shortcuts
- Can have each platform in single one

**Comment by codeyash** [comment]
UI modification is required to support visual way of editing keys.

Required changes:
- Json parse and Save
- Combobox for showing all possible options
- Default for each platform
- Settings must be saved in INI 
- No Sqlite is required at all.
- Add copy button in UI

**Comment by codeyash** [comment]
One can extend and use any shortcuts of any editor/platform.

Simple copy from keymap folder and edit . Also there is UI way of editing shortcuts/Copy keymaps.

All done :)
