### ISSUE TITLE
Text Editor shows black text with black background

### ISSUE THREAD

**Issue by samratchak** [speedovation/kiwi#109]
I selected Darkblue theme with cold editor theme. closed the tool and reopened it. The main text editor shows black text on black background except for the color codes, which show up in white or gray with a white background.

**Comment by codeyash** [comment]
Fixed a similar case

If current find dialog and try to change scheme it leaves bad screen. Also for finding text added a delay to make look it smooth and responsive all time.

**Comment by codeyash** [comment]
Default and Dark are complete themes

Soon work on rest

**Comment by codeyash** [comment]
Solved
