### ISSUE TITLE
Drag and Create Project

### ISSUE THREAD

**Issue by codeyash** [speedovation/kiwi#90]
On Project explorer by dragging folder it should create project space.
1. Read folder path
2. Parse and add files & folders recursively
3. Save Project file. 

Decide New file extension of project.
1. KiWi_Project.Kw
2. Project.Kw
3. Project.Kiwi

**Comment by samratchak** [comment]
Project extension should have 3 characters. Try Project.kwx if you are using XML to store your project structure and Project.kwj for JSON based structure. Other extensions can follow this naming convention. For e.g.:- Theme.ktx for Kiwi Themes structured with XML or Theme.ktj for JSON structure.

**Comment by codeyash** [comment]
Project Manager Changes way it was working

It loads root folder only
On Click it will load that selected folder only and caches it. Next time it will just show items and no live loading.

**Comment by codeyash** [comment]
It opens any folder as project without saving in session

Another issue provides menu options to save in session if required

Project.KWI is fixed for now.
